### ISSUE TITLE
기능 TODO-List

### ISSUE THREAD

**Issue by Je-chan** [codestates/triplus#2]
# 시스템 아키텍처

- [ ] JWT를 이용한 로그인 구현 
- [ ] 권한 부여(Authorization)에 따른 기능의 접근 제한 구현 (일반 사용자, 관리자 권한)
- [ ] OAuth 2.0을 이용한 소셜 로그인 
- [ ] socket.io를 이용한 실시간 통신 
    
# UI / UX
- [ ] 회원가입, 로그인, 로그아웃, 마이페이지, 회원탈퇴 기능 구현 
- [ ] 회원가입, 로그인 및 회원정보 수정 시 유효성 검사 
- [ ] 소셜 로그인 외 서비스 자체 회원가입 기능 제공
- [ ] 회원가입 없이 '체험하기' 형식으로 가볍게 기능을 이용할 수 있는 장치 마련
- [ ] 회원 탈퇴나 리소스 삭제시 확인(confirm) 모달 제공 
- [ ] 마이페이지를 통해 사용자 개인정보 수정 기능 제공 
- [ ] (소셜 로그인이 아닐 경우) 비밀번호 수정 기능 제공 
- [ ] 라이브러리를 사용하지 않고 React 컴포넌트 직접 작성 (유어클래스에서 다룬 것: 탭, 드랍다운, 모달 등)  
- [ ] 검색 필터링 기능
- [ ] 모바일 환경 대응 및 반응형 웹 
- [ ] 라이브러리를 사용하지 않고 React 컴포넌트 직접 작성 (유어클래스에서 다루지 않은 것) 
- [ ] S3로 파일 업로드
- [ ] 회원 가입시 인증 메일 발송
- [ ] 스케쥴러(cron)에 의한 메일 전송 
- [ ] 위치 기반 기능  
- [ ] 스크롤에 의한 애니메이션 적용 (greensock 사용 권장)
- [ ] Socket.io를 이용한 채팅 기능
- [ ] 지도 API 사용 (오버레이, 핀)
- [ ] Canvas, SVG를 활용한 동적인 이미지 표시 
    
# 스키마 및 API
- [ ] N:M (다대다) 관계 설정
- [ ] ERD (DB Diagram) 작성 
- [ ] API 작성 툴 (Swagger, Postman, Gitbook API) 을 사용하여 요청/응답 및 JSON 키/값 형식 기술
- [ ] ORM 사용 
    
# DevOps
- [x] #3
- [x] 깃허브 커밋메세지 규칙 합의
- [x] 버전 규칙 합의
- [x] PR 형식 합의
- [ ] 배포 자동화 설정 
- [ ] 도메인 구매 및 HTTPS 배포
